// export const ZONE_DETAILS_LIST_REQUEST = "ZONE_DETAILS_LIST_REQUEST";
// export const ZONE_DETAILS_LIST_SUCCESS = "ZONE_DETAILS_LIST_SUCCESS";
// export const ZONE_DETAILS_LIST_FAIL = "ZONE_DETAILS_LIST_FAIL";
// export const ZONE_DETAILS_LIST_RESET = "ZONE_DETAILS_LIST_RESET";
